### ISSUE TITLE
ImportError: No module named mido.backends.portmidi

### ISSUE THREAD

**Issue by ericyd** [mido/mido#17]
I am using mido in a program which I am now trying to bundle into an executable using pyinstaller.  When I run the resulting executable file, I get the following error output:

```
Traceback (most recent call last):
  File "<string>", line 44, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_-py2.7.egg/PyInstaller/load/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/home/eric/Documents/School/Independent/py/build/gui-edit/out00-PYZ.pyz/mido", line 117,   in <module>
  File "/home/eric/Documents/School/Independent/py/build/gui-edit/out00-PYZ.pyz/mido", line 110, in set_backend
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/__init__.py", line 52, in __init__
    find_dotted_module(self.name)
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/__init__.py", line 22, in find_dotted_module
    raise ImportError('No module named {}'.format(name))
ImportError: No module named mido.backends.portmidi
```

Running the `script.py` file works perfectly with mido and no errors arise regarding importing the backend.  I have tried editing my pyinstaller `script.spec` file to include all the relevant mido directories in the 'hiddenimports'.  Any ideas why this error would pop up here?

I am running LinuxMint 17.

**Comment by luciakuschnir** [comment]
Hello, I´m trying to install mido in windows 7. I'm very new on Python so may be is very easy, but I cannot understand what's happen....
Thank you in advanced!
Lucía K.

I try to import mido and:
ImportError: No module named mido.backends.portmidi
I found this: http://mido.readthedocs.org/en/latest/backends.html, but I cannot do anything because I cannot import mido...
Then, looking here I try again and:
ImportError: cannot import name ports
So I don't know.... On OS X Yosemite runs perfect...I read mido should work on windows, but I cannot install it...

**Comment by olemb** [comment]
It sounds like you're running an old version of Mido. I removed the code
that looks for mido.backends.portmidi in 1.1.7. (The latest version is
1.1.12.)

How did you install it?

There could possible be something else going on. Could you send me a full
backtrace?

**Comment by olemb** [comment]
Traceback I mean. :) Basically everything Python says when it fails to import the module.

**Comment by demcanulty** [comment]
Just wanted to say thanks!  Using the explicit 
```
import mido.backends.portmidi 
```
fixed my pyinstaller problems here :)
