### ISSUE TITLE
OSError: no ports available - on windows?

### ISSUE THREAD

**Issue by lorenzofattori** [mido/mido#218]
I'm just trying the receiver function, I want to write a small program that gets midi notes and CC and do things.
I'm running python 3.7 on windows, trying to rung the example I get this:

MidiInWinMM::initialize: no MIDI input devices currently available.

Traceback (most recent call last):
  File "c:/xxx/midiTest.py", line 12, in <module>
    with mido.open_input(portname) as port:
  File "C:\xxx\lib\site-packages\mido\backends\backend.py", line 90, in open_input
    return self.module.Input(name, **self._add_api(kwargs))
  File "C:\xxx\lib\site-packages\mido\ports.py", line 164, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\xxx\lib\site-packages\mido\ports.py", line 88, in __init__
    self._open(**kwargs)
  File "C:\xxx\lib\site-packages\mido\backends\rtmidi.py", line 167, in _open
    virtual=virtual, api=self.api)
  File "C:\xxx\lib\site-packages\mido\backends\rtmidi.py", line 126, in _open_port
    raise IOError('no ports available')
OSError: no ports available

rtmidi is installed

any idea?

**Comment by lorenzofattori** [comment]
I didn't have a midi interface, installed loopMIDI and fixed it
