### ISSUE TITLE
PyInstaller - No module named 'mido.backends.rtmidi'

### ISSUE THREAD

**Issue by garrettluskey** [mido/mido#219]
I was having trouble deploying a project using mido.

Here is some example code for testing deployment

_deployment_test.py_
```python
import mido

if __name__ == "__main__":
    print(mido.get_output_names())
```

This file compiles through PyInstaller. However, the exe will not execute as shown with the error below.

```
..\dist\deployment_test>deployment_test.exe
Traceback (most recent call last):
  File "deployment_test.py", line 4, in <module>
  File "site-packages\mido\backends\backend.py", line 175, in get_output_names
  File "site-packages\mido\backends\backend.py", line 162, in _get_devices
  File "site-packages\mido\backends\backend.py", line 42, in module
  File "site-packages\mido\backends\backend.py", line 58, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mido.backends.rtmidi'
[14584] Failed to execute script deployment_test
```

**Fix**
The fix for this is quite simple. Assume this may happen for other backends, adding an import for whatever backend is being used will have PyInstaller include it in the build and distribution.

_deployment_test.py_

```python
import mido
import mido.backends.rtmidi

if __name__ == "__main__":
    print(mido.get_output_names())
```

I wanted to add this as an issue in the case others are experiencing this problem. I also believe that mido should be able to be built using PyInstaller without this workaround.

**Comment by ho0ber** [comment]
@garrettluskey You just saved me a lot of time. Thank you!
