### ISSUE TITLE
meta.py: ValueError: variable int must be a positive integer

### ISSUE THREAD

**Issue by csarami** [mido/mido#243]
Hi,

In my code I get

```
Traceback (most recent call last):
  File "Midi Projects/symbolToChord_v1.py", line 160, in <module>
    mo.save("songWithChords.mid") 
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mido/midifiles/midifiles.py", line 432, in save
    self._save(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mido/midifiles/midifiles.py", line 445, in _save
    write_track(outfile, track)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mido/midifiles/midifiles.py", line 251, in write_track
    data.extend(encode_variable_int(msg.time))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mido/midifiles/meta.py", line 112, in encode_variable_int
    raise ValueError('variable int must be a positive integer')
ValueError: variable int must be a positive intege
```
I suppose I am running the latest version on MIDO. 
```
pip freeze | grep mido
mido==1.2.9
```

what am doing wrong?

Any help would be greatly appreciated.

**Comment by rdoursenaud** [comment]
It looks like you have a `Message` with an incompatible `time` value.
Could you please provide a bit of the context an what you're trying to achieve, like a code snippet?
