### ISSUE TITLE
Resource leak and crash in get_output_names()

### ISSUE THREAD

**Issue by TheOtherDays** [mido/mido#256]
This code:
```python
import mido

for i in range(0, 100):
	print(i)
	p = mido.get_output_names()
	del p
```
crashes on linux after 32 iterations (v 1.2.9, tested on multiple computers)

Output:
```python
0
1
2
3
[...]
30
31
32
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Cannot allocate memory
Traceback (most recent call last):
  File "src/_rtmidi.pyx", line 818, in rtmidi._rtmidi.MidiIn.__cinit__
RuntimeError: MidiInAlsa::initialize: error creating ALSA sequencer client object.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "p.py", line 5, in <module>
    p = mido.get_output_names()
  File "/home/eric/.local/lib/python3.8/site-packages/mido/backends/backend.py", line 175, in get_output_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/home/eric/.local/lib/python3.8/site-packages/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/home/eric/.local/lib/python3.8/site-packages/mido/backends/rtmidi.py", line 52, in get_devices
    input_names = set(rtmidi.MidiIn(rtapi=rtapi).get_ports())
  File "src/_rtmidi.pyx", line 820, in rtmidi._rtmidi.MidiIn.__cinit__
rtmidi._rtmidi.SystemError: MidiInAlsa::initialize: error creating ALSA sequencer client object.
```

RtMidi's ``get_ports()`` do leak some resources and must be explicitely freed (see https://github.com/SpotlightKid/python-rtmidi/issues/60#issuecomment-609437630).

The following patch prevents the leak and the crash:

```diff
--- mido/backends/rtmidi.py	2020-12-17 22:54:07.115227374 +0100
+++ /tmp/rtmidi.py	2020-12-17 22:53:48.254984192 +0100
@@ -48,9 +48,10 @@
     devices = []
 
     rtapi = _get_api_id(api)
-
-    input_names = set(rtmidi.MidiIn(rtapi=rtapi).get_ports())
-    output_names = set(rtmidi.MidiOut(rtapi=rtapi).get_ports())
+    mi = rtmidi.MidiIn(rtapi=rtapi)
+    mo = rtmidi.MidiOut(rtapi=rtapi)
+    input_names = set(mi.get_ports())
+    output_names = set(mo.get_ports())
 
     for name in sorted(input_names | output_names):
         devices.append({'name': name,
@@ -58,6 +59,8 @@
                         'is_output': name in output_names,
                         })
 
+    mi.delete()
+    mo.delete()
     return devices
```
I can make a pull request if you want.

NB: it seems related tp https://github.com/mido/mido/issues/236, but this is worse ;-)

Thank you

**Comment by olemb** [comment]
Thanks for the report! This is pretty bad leakage. I was not aware that `delete()` had to be called to free memory. I guess the same is true in the port `close()` method:

```
      class PortCommon(object):
          def _close(self):
              self._rt.close_port()
+            self._rt.delete()
```

A pull request would be great! I will get this into the next release. (I have started up work on Mido again and am hoping to have a new release out soon.)

**Comment by TheOtherDays** [comment]
Here is my pull request: https://github.com/mido/mido/pull/264

Thank you

**Comment by olemb** [comment]
Thanks!
