### ISSUE TITLE
WindowsError: [Error 126] The specified module could not be found

### ISSUE THREAD

**Issue by ghost** [mido/mido#27]
Trying to play a midi file yields this result:

Traceback (most recent call last):
  File "C:\Python27\Lib\mido-master\examples\midifiles\play_midi_file.py", line 19, in <module>
    with mido.open_output(port_name) as output:
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\backend.py", line 133, in open_output
    return self.module.Output(name, **self._add_api(kwargs))
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\backend.py", line 63, in module
    self.load()
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\backend.py", line 79, in load
    self._module = _import_module(self.name)
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\backend.py", line 25, in _import_module
    return importlib.import_module(module, package)
  File "C:\Python27\lib\importlib__init__.py", line 37, in import_module
    **import**(name)
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\portmidi.py", line 16, in <module>
    from . import portmidi_init as pm
  File "C:\Python27\lib\site-packages\mido-1.1.13-py2.7.egg\mido\backends\portmidi_init.py", line 20, in <module>
    lib = CDLL(dll_name)
  File "C:\Python27\lib\ctypes__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

What am I doing wrong? Is the .dll in the wrong location?

**Comment by olemb** [comment]
Yes, it looks like portmidi.dll is not in the search path. How did you install PortMidi?

**Comment by MIDIPython** [comment]
I tried to build the solution based on the instructions given in the source, I'm gonna try a fresh copy.

**Comment by notinachos** [comment]
I am having this same issue on Windows. I installed mido using pip. For a temporary workaround, I've copied portmidi.dll to my Python script's directory.

**Comment by tinaheidinger** [comment]
I'm having a similar issue on OS X El Capitan:
```
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libportmidi.dylib, 6): image not found
```

**Comment by meatcomputer** [comment]
I tried for days to get portmidi and mido to play nicely on windows 7 with almost no luck. Finally, I just installed pygame and changed the backend. Worked like a charm!

**Comment by rdoursenaud** [comment]
Is this still relevant with the current release?

**Comment by rdoursenaud** [comment]
No reply, closing.
