### ISSUE TITLE
Unexpected exception on iterate over some MIDI files

### ISSUE THREAD

**Issue by dogtopus** [mido/mido#319]
```
>>> mid = mido.MidiFile('Mariage-dAmour.mid')
>>> for msg in mid:
...     pass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<venv path redacted>/lib/python3.9/site-packages/mido/midifiles/midifiles.py", line 384, in __iter__
    for msg in merge_tracks(self.tracks):
  File "<venv path redacted>/lib/python3.9/site-packages/mido/midifiles/tracks.py", line 110, in merge_tracks
    messages.extend(_to_abstime(track))
  File "<venv path redacted>/lib/python3.9/site-packages/mido/midifiles/tracks.py", line 68, in _to_abstime
    yield msg.copy(time=now)
  File "<venv path redacted>/lib/python3.9/site-packages/mido/midifiles/meta.py", line 507, in copy
    return self.__class__(**attrs)
TypeError: __init__() got an unexpected keyword argument 'type'
```

Looking at the MIDI file, there are some unknown meta messages. Not sure if related.

[sample MIDI file that reproduces this issue](https://github.com/mido/mido/files/6714286/Mariage-dAmour.zip)

**Comment by dogtopus** [comment]
Potentially related PR: #286

**Comment by cduck** [comment]
I see the same `TypeError` issue on this file:
[Sample MIDI file](https://github.com/mido/mido/files/7533306/Hakuouki.Shinsengumi.Kitan.-.Sakurabana.mid.zip)
