### ISSUE TITLE
Management of data > 127 on 'sysex' messages

### ISSUE THREAD

**Issue by beppemiletto** [mido/mido#334]
Goog evening,
I am trying to use mido to manage a control surface "Novation LAUNCHPAD".
From Novation documentation many sysex messages contain data bytes > 127:
For example the device enquiry 

Device Inquiry
Host >> Launchpad MK2: | F0h 7Eh 7Fh 06h 01h F7h
                                           (240,126,127, 6, 1, 247)
Launchpad MK2 will respond:
Launchpad MK2 >> Host:   F0h 7Eh device ID 06h 02h 00h 20h 29h 69h 00h 00h 00h &lt;firmware revision 4 Bytes; F7h
                                          (240,126, device ID, 6, 2, 0, 32, 41,105, 0, 0, 0,&lt;firmware revision 4 bytes, 247)

But when I try froming the message to be sent i receive

Traceback (most recent call last):
  File "D:/project/autogui/midisysex.py", line 17, in <module>
    msg = mido.Message('sysex', data=[240,126,127, 6, 1, 247])
  File "D:\project\autogui\venv\lib\site-packages\mido\messages\messages.py", line 114, in __init__
    check_msgdict(msgdict)
  File "D:\project\autogui\venv\lib\site-packages\mido\messages\checks.py", line 99, in check_msgdict
    check_value(name, value)
  File "D:\project\autogui\venv\lib\site-packages\mido\messages\checks.py", line 86, in check_value
    _CHECKS[name](value)
  File "D:\project\autogui\venv\lib\site-packages\mido\messages\checks.py", line 37, in check_data
    check_data_byte(byte)
  File "D:\project\autogui\venv\lib\site-packages\mido\messages\checks.py", line 58, in check_data_byte
    raise ValueError('data byte must be in range 0..127')
ValueError: data byte must be in range 0..127

Process finished with exit code 1:

Is there a way to send and receive MIDI data full byte FFh?

**Comment by olemb** [comment]
240 and 247 are the start and stop bytes of the message and are not part of the sysex data. If you remove them it should work expected:

```
mido.Message('sysex', data=[126,127, 6, 1])
```
