### ISSUE TITLE
Midi file parsing problem

### ISSUE THREAD

**Issue by eeyrw** [mido/mido#345]
Problem midi file:
[Vivaldi_-_Summer_-_Piano.zip](https://github.com/mido/mido/files/7575976/Vivaldi_-_Summer_-_Piano.zip)

Code snippet:
```
def readMidiFile(filePath):
    noteOnList = []
    mid = MidiFile(filePath)
    print('MIDI duration:', mid.length)
    absoluteTime = 0
    for msg in mid:
        absoluteTime += msg.time
        if msg.type == 'note_on' and msg.velocity is not 0 and msg.channel is not 9:
            noteOnList.append((absoluteTime, msg.note))

    noteOnList.sort(key=lambda x: x[0])
    noteOnList.append((mid.length, 128))  # Add End-of-midi tag

    return noteOnList
```

Error report:
```
Traceback (most recent call last):
.......
  File "C:\Users\yuan\Desktop\midi-to-simplescore\MidiToSimpleScore.py", line 208, in main
    noteOnList = readMidiFile(filePath)
  File "C:\Users\yuan\Desktop\midi-to-simplescore\MidiToSimpleScore.py", line 18, in readMidiFile
    print('MIDI duration:', mid.length)
  File "C:\Python\lib\site-packages\mido\midifiles\midifiles.py", line 375, in length
    return sum(msg.time for msg in self)
  File "C:\Python\lib\site-packages\mido\midifiles\midifiles.py", line 375, in <genexpr>
    return sum(msg.time for msg in self)
  File "C:\Python\lib\site-packages\mido\midifiles\midifiles.py", line 384, in __iter__
    for msg in merge_tracks(self.tracks):
  File "C:\Python\lib\site-packages\mido\midifiles\tracks.py", line 110, in merge_tracks
    messages.extend(_to_abstime(track))
  File "C:\Python\lib\site-packages\mido\midifiles\tracks.py", line 68, in _to_abstime
    yield msg.copy(time=now)
  File "C:\Python\lib\site-packages\mido\midifiles\meta.py", line 507, in copy
    return self.__class__(**attrs)
TypeError: __init__() got an unexpected keyword argument 'type'
```

**Comment by pr0jectile** [comment]
Does this help by any chance? Added `if not msg.is_meta:` before `absoluteTime += msg.time`

```python
def readMidiFile(filePath):
    noteOnList = []
    mid = MidiFile(filePath)
    print('MIDI duration:', mid.length)
    absoluteTime = 0
    for msg in mid:
        if not msg.is_meta: # skipping is_meta messages
            absoluteTime += msg.time
            if msg.type == 'note_on' and msg.velocity != 0 and msg.channel != 9:
                noteOnList.append((absoluteTime, msg.note))

    noteOnList.sort(key=lambda x: x[0])
    noteOnList.append((mid.length, 128))  # Add End-of-midi tag

    return noteOnList
```

**Comment by eeyrw** [comment]
> Does this help by any chance? Added `if not msg.is_meta:` before `absoluteTime += msg.time`
> 
> ```python
> def readMidiFile(filePath):
>     noteOnList = []
>     mid = MidiFile(filePath)
>     print('MIDI duration:', mid.length)
>     absoluteTime = 0
>     for msg in mid:
>         if not msg.is_meta: # skipping Meta messages
>             absoluteTime += msg.time
>             if msg.type == 'note_on' and msg.velocity != 0 and msg.channel != 9:
>                 noteOnList.append((absoluteTime, msg.note))
> 
>     noteOnList.sort(key=lambda x: x[0])
>     noteOnList.append((mid.length, 128))  # Add End-of-midi tag
> 
>     return noteOnList
> ```

Thank for you suggestion. But it does not help. Beacuse the expection happens in the line "print('MIDI duration:', mid.length)".  I finally find out that someone has corrected this bug and submit PR:https://github.com/mido/mido/pull/286
