### ISSUE TITLE
La Campanella throwing 'AttributeError: sysex message has no attribute channel' error

### ISSUE THREAD

**Issue by pr0jectile** [mido/mido#349]
Hi guys, I'm trying to read La Campanella by Frank Liszt but I keep getting this error:

```python
Traceback (most recent call last):
  File "......../midiparser.py", line 31, in <module>
    msg.channel = k
  File "......../modules/mido/messages/messages.py", line 172, in _setattr
    raise AttributeError('{} message has no '
AttributeError: sysex message has no attribute channel
```

Here's the section of code that's throwing an error (line 31 is `msg.channel = k`):

```python
# Assign Tracks to different channels before merging to know the message origin
for k in range(len(mid.tracks)):
    for msg in mid.tracks[k]:
        if not msg.is_meta:
            msg.channel = k
```

Here's the MIDI file and MP3 file:

[La Campanella.zip](https://github.com/mido/mido/files/7739637/La.Campanella.zip)

How can I create a single channel for tracks that don't have a channel? Kind of new to scripting in python.

Thanks.

**Comment by pr0jectile** [comment]
Fixed this, but may be a poor implementation. I used the following:
```python
    for k in range(len(mid.tracks)):
        for msg in mid.tracks[k]:
            if not msg.is_meta and msg.type in ['note_on', 'note_off']:
                msg.channel = k
```
Hope this helps someone having similar issues!
