### ISSUE TITLE
Bug: Opening ports repeatedly creates duplicate RtMidi ports

### ISSUE THREAD

**Issue by EFeru** [mido/mido#357]
Hi,

When using mido to open ports repeatedly, duplicates RtMidiOut ports are created.

This is my test python script:
```py
import mido
import time

if __name__ == '__main__':

    outport = None
    port = "CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0"

    while True:
        print(mido.get_input_names())
        try:
            if outport != None:
                outport.close()
                time.sleep(0.2)
                print ("Port closed")
            outport = mido.open_output(port)
        except:
            print("Cannot open port")
        time.sleep(1)
```

This is the output, (As it can be seen a port is created everytime the `open_output` is called again):
```
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'rtpmidi raspberrypi:Network 128:0']
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'RtMidiOut Client:RtMidi output 134:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'RtMidiOut Client:RtMidi output 134:0', 'RtMidiOut Client:RtMidi output 137:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'RtMidiOut Client:RtMidi output 134:0', 'RtMidiOut Client:RtMidi output 137:0', 'RtMidiOut Client:RtMidi output 140:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'RtMidiOut Client:RtMidi output 134:0', 'RtMidiOut Client:RtMidi output 137:0', 'RtMidiOut Client:RtMidi output 140:0', 'RtMidiOut Client:RtMidi output 143:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
...
```

If I wait for a while then it crashes:
```
['CASIO USB-MIDI:CASIO USB-MIDI MIDI 1 20:0', 'Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 131:0', 'RtMidiOut Client:RtMidi output 134:0', 'RtMidiOut Client:RtMidi output 137:0', 'RtMidiOut Client:RtMidi output 140:0', 'RtMidiOut Client:RtMidi output 143:0', 'RtMidiOut Client:RtMidi output 146:0', 'RtMidiOut Client:RtMidi output 149:0', 'RtMidiOut Client:RtMidi output 152:0', 'RtMidiOut Client:RtMidi output 155:0', 'RtMidiOut Client:RtMidi output 158:0', 'RtMidiOut Client:RtMidi output 161:0', 'RtMidiOut Client:RtMidi output 164:0', 'RtMidiOut Client:RtMidi output 167:0', 'RtMidiOut Client:RtMidi output 170:0', 'RtMidiOut Client:RtMidi output 173:0', 'RtMidiOut Client:RtMidi output 176:0', 'RtMidiOut Client:RtMidi output 179:0', 'RtMidiOut Client:RtMidi output 182:0', 'RtMidiOut Client:RtMidi output 185:0', 'RtMidiOut Client:RtMidi output 188:0', 'rtpmidi raspberrypi:Network 128:0']
Port closed
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Cannot allocate memory
Traceback (most recent call last):
  File "src/_rtmidi.pyx", line 818, in rtmidi._rtmidi.MidiIn.__cinit__
RuntimeError: MidiInAlsa::initialize: error creating ALSA sequencer client object.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mido.py", line 10, in <module>
    print(mido.get_input_names())
  File "/usr/local/lib/python3.7/dist-packages/mido/backends/backend.py", line 169, in get_input_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/usr/local/lib/python3.7/dist-packages/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/usr/local/lib/python3.7/dist-packages/mido/backends/rtmidi.py", line 52, in get_devices
    input_names = set(rtmidi.MidiIn(rtapi=rtapi).get_ports())
  File "src/_rtmidi.pyx", line 820, in rtmidi._rtmidi.MidiIn.__cinit__
rtmidi._rtmidi.SystemError: MidiInAlsa::initialize: error creating ALSA sequencer client object.

```

Any idea how to fix this or close/reset the duplicated RtMmidiOut ports?

**Comment by cyberic99** [comment]
It might be related to this issue:

https://github.com/mido/mido/issues/256

**Comment by EFeru** [comment]
@cyberic99 Thanks that is exactly the issue I have too. Do you know if a release is available?

**Comment by cyberic99** [comment]
Tag 1.2.10 fixed the issue, I think

**Comment by EFeru** [comment]
Oh when I check my version or try to install latest I get this:
![image](https://user-images.githubusercontent.com/24780745/152639865-01cd0baa-2b5c-467c-b98a-72e7eeb5e2e3.png)

**Comment by EFeru** [comment]
Fixed. I had to upgrade:
```
sudo pip3 install mido --upgrade
```
![image](https://user-images.githubusercontent.com/24780745/152641630-fecf51b2-95ce-409b-a747-2117d55a70ba.png)


On https://pypi.org/simple/mido/ the latest version 1.2.10 is already present.
