### ISSUE TITLE
Can not create a Virtual Port with rtmidi on windows

### ISSUE THREAD

**Issue by paoloros97** [mido/mido#375]
Hello, 

I've tried this:
`inport = mido.open_input('emulatore', virtual=True)`

But i got the following error:

_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Paolo\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\backends\backend.py", line 91, in open_input
    return self.module.Input(name, **self._add_api(kwargs))
  File "C:\Users\Paolo\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\ports.py", line 161, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Users\Paolo\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\ports.py", line 86, in __init__
    self._open(**kwargs)
  File "C:\Users\Paolo\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\backends\rtmidi.py", line 129, in _open
    self.name = _open_port(self._rt, self.name, client_name=client_name,
  File "C:\Users\Paolo\AppData\Local\Programs\Python\Python310\lib\site-packages\mido\backends\rtmidi.py", line 84, in _open_port
    rt.open_virtual_port(name)
  File "src/_rtmidi.pyx", line 642, in rtmidi._rtmidi.MidiBase.open_virtual_port_
**NotImplementedError: Virtual ports are not supported by the Windows MultiMedia API.**

**Comment by rdoursenaud** [comment]
Hi!

The virtualports provided by rtmidi cannot be used with Microsoft Windows as they rely on it being implemented at the OS level which is not the case with the Windows MultiMedia API.
This is expected. Maybe we should update the documentation to reflect this.

In the meantime I recommend you look at [PyTEMIDI](https://github.com/complynx/pytemidi) and/or try this patch: https://github.com/mido/mido/pull/361

Good luck.
