### ISSUE TITLE
format_as_string fails on time_signature meta messages

### ISSUE THREAD

**Issue by aarontp** [mido/mido#376]
Calling `format_as_string` on a MetaMessage with `time_signature` type results in the following error:

```
Traceback (most recent call last):
  File "/home/a/src/midi-stego/./midi-stego.py", line 374, in <module>
    print_messages(args.input_file)
  File "/home/a/src/midi-stego/./midi-stego.py", line 158, in print_messages
    log.info('\t{0!s}'.format(mido.format_as_string(message)))
  File "/home/a/.local/share/virtualenvs/pypeggiator-3C5MqlNB/lib/python3.9/site-packages/mido/messages/messages.py", line 254, in format_as_string
    return msg2str(vars(msg), include_time=include_time)
  File "/home/a/.local/share/virtualenvs/pypeggiator-3C5MqlNB/lib/python3.9/site-packages/mido/messages/strings.py", line 6, in msg2str
    spec = SPEC_BY_TYPE[type_]
KeyError: 'time_signature'
```

It looks like there is no `time_signature` attribute in `SPECS` here:
https://github.com/mido/mido/blob/5fd6c9d5da1b21a7dab6013d9a170fd2959d3c74/mido/messages/specs.py#L35

My guess is that most of the other meta message types will fail as well given that they don't appear to be represented there.

**Comment by rdoursenaud** [comment]
As outlined by [the documentation](https://mido.readthedocs.io/en/latest/string_encoding.html?highlight=format_as_string#string-encoding), serializing is only supported for `Message`.
Passing anything else should raise a `TypeError` exception.

**Comment by rdoursenaud** [comment]
The proper fix is to differentiate MIDI messages and events. While message events can be very similar to messages meta events cannot and this creates all sorts of weird behavior with those.
Thus I postpone fixing this in the next release cycle.
