### ISSUE TITLE
rtmidi AttributeError on MacOS

### ISSUE THREAD

**Issue by JC3** [mido/mido#604]
**Describe the bug**

When attempting to use the default rtmidi backend on MacOS, mido appears to use an undefined named constant from rtmidi, generating an `AttributeError`.

**To Reproduce**

```python
import mido
mido.get_input_names()
```

**Expected behavior**

Correct functioning.

**Actual behavior**

```
Python 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mido
>>> mido.get_input_names()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cipriani_pro2023/pyenv-brixtui/lib/python3.11/site-packages/mido/backends/backend.py", line 174, in get_input_names
    devices = self._get_devices(**self._add_api(kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cipriani_pro2023/pyenv-brixtui/lib/python3.11/site-packages/mido/backends/backend.py", line 168, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cipriani_pro2023/pyenv-brixtui/lib/python3.11/site-packages/mido/backends/rtmidi.py", line 54, in get_devices
    rtapi = _get_api_id(api)
            ^^^^^^^^^^^^^^^^
  File "/Users/cipriani_pro2023/pyenv-brixtui/lib/python3.11/site-packages/mido/backends/rtmidi.py", line 38, in _get_api_id
    return rtmidi.API_UNSPECIFIED
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'
```

**Context (please complete the following information):**
- Operating system name & version: MacOS 13.6.6
- Python version: 3.10.x, 3.11.x
- mido package version (Retrievable using `mido.version_info`) & installation method (Distribution repository, PyPI, source…): 1.3.3 from PyPi
- backend used (amidi, portmidi, rtmidi, PyGame…): python-rtmidi

**Comment by rdoursenaud** [comment]
Hi and thanks for the report.

Unfortunately I can’t reproduce the issue.

Please check that `python-rtmidi` is properly installed into your environment and report the version used:
```py
import rtmidi
rtmidi.__version__
```

Please note that `rtmidi` is not automatically installed alongside `mido` unless you specify it using the `[ports-rtmidi]` selector as [outlined in our documentation](https://mido.readthedocs.io/en/latest/installing.html).
```py
python3 -m pip install mido[ports-rtmidi]
```

Alternatively you can install it manually after `mido`:
```py
python3 -m pip install python-rtmidi
```

Please report back.

**Comment by snej** [comment]
Clarification — my experience was that installing Mido itself (`python3 -m pip install mido`) resulted in a different exception when opening a port, because no back-end was installed at all. 

Then I tried to fix the installation by running `python3 -m pip install rtmidi`, which succeeded, but now the exception changed to the one described above.

Then I tried `python3 -m pip install mido[ports-rtmidi]`, copied straight from the docs, which failed because zsh tries to interpret the brackets as metacharacters; the command _should_ be `python3 -m pip install 'mido[ports-rtmidi]’`. This worked.

**Comment by rdoursenaud** [comment]
Thank you for sharing your experience.

I’ll try and make this more straightforward for version 2.

I still like to provide the ability to use mido to manipulate MIDI data as objects without handling the communication itself. I want to keep the library as flexible as possible for application users.

In the meantime, I’ll update the documentation to better outline that you *need* to install a ports backend if you intend to send or receive messages and make mido issue a proper warning if you do so without one installed.
